version: '3'

tasks:

  test:all:
    desc: Run AGP + Reviewer Agent + Run unit and integration tests inside Docker
    cmds:
      - set -e 
      - echo "Starting AGP + Reviewer Agent..."
      - docker compose -f docker-compose.yaml up -d --build
      - echo "⏳ Waiting for services to be ready..."
      - sleep 10
      - echo "🧪 Running Unit and Integration tests.."
      - docker exec tf-reviewer-agent pytest tests
      - echo "🧼 Shutting down containers..."
      - docker compose down
   
  test:local:
      desc: Run only local Pytest tests (no Compose)
      cmds:
        - echo "🧪 Running Unit and Integration tests..."
        - pytest tests/
  
  test:local-langsmith:
      desc: Run only local Pytest tests (no Compose)
      cmds:
        - echo "🧪 Running Unit tests..."
        - pytest tests/unit
        - echo "🧪 Running Integration tests..."
        - pytest --langsmith-output tests/integration