name: helm push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"
  workflow_dispatch:


jobs:
  chart:
    name: Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Simplified to latest stable version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Helm
        uses: azure/setup-helm@v4 # Simplified to latest stable version
        with:
          version: "3.12.1" # Default Helm version

      - name: Helm lint
        run: helm lint deployments/helm/tf-code-reviewer-agntcy-agent --with-subcharts

      - name: Package and Push Helm Chart
        run: |
          # Extract the version from Chart.yaml
          CHART_VERSION=$(grep '^version:' deployments/helm/tf-code-reviewer-agntcy-agent/Chart.yaml | awk '{print $2}')

          # Package and push the Helm chart
          helm package deployments/helm/tf-code-reviewer-agntcy-agent --dependency-update --version $CHART_VERSION
          helm push tf-code-reviewer-agntcy-agent-$CHART_VERSION.tgz oci://ghcr.io/${{ github.repository_owner }}/helm
