name: Run Terraform Code Reviewer Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      LANGSMITH_TRACING: true
      LANGSMITH_ENDPOINT: ${{ secrets.LANGSMITH_ENDPOINT }}
      LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
      LANGSMITH_PROJECT: ${{ secrets.LANGSMITH_PROJECT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
      AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"

      - name: Install Task (Taskfile runner)
        run: |
          curl -sSL https://taskfile.dev/install.sh | sh
          sudo mv ./bin/task /usr/local/bin/task

      - name: Run integration tests with Taskfile
        run: |
          task test:integration